# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-29 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0025_auto_20160701_1735'),
        ('vi_municipales_2016', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateposiblefacebookpage',
            name='candidate',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.Candidate'),
        ),
    ]
