# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-29 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vi_municipales_2016', '0002_candidateposiblefacebookpage_candidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidatePosibleFacebookPage',
            new_name='PosibleFacebookPage',
        ),
    ]
